ubuntu@ip-172-31-29-242:~/udacity-project04$ ./run_kubernetes.sh
tamln2
Error from server (AlreadyExists): pods "my-project" already exists
tamln3
NAME         READY   STATUS    RESTARTS   AGE
my-project   1/1     Running   0          11m
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080

ubuntu@ip-172-31-29-242:~/udacity-project04/output_txt_files$ kubectl logs my-project
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 201-481-349
[2023-03-24 21:48:47,094] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2023-03-24 21:48:47,104] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-03-24 21:48:47,112] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-03-24 21:48:47,114] INFO in app: output prediction: [20.35373177134412]
127.0.0.1 - - [24/Mar/2023 21:48:47] "POST /predict HTTP/1.1" 200 -
[2023-03-24 21:54:16,598] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2023-03-24 21:54:16,607] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-03-24 21:54:16,614] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2023-03-24 21:54:16,617] INFO in app: output prediction: [20.35373177134412]
127.0.0.1 - - [24/Mar/2023 21:54:16] "POST /predict HTTP/1.1" 200 -
